on:
  push:
    branches:
      - master

name: Publish
jobs:
  release:
    name: PR Merges
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Release
        if: endsWith(github.event.head_commit.message, '[ci skip]') == false
        uses: actions/npm@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: make release-ci
