on:
  push:
    branches:
      - master

name: Publish
jobs:
  release:
    name: PR Merges
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Check Skip CI commits
        uses: veggiemonk/skip-commit@master
        env:
          COMMIT_FILTER: chore(release)
      - run: git config --global user.email "kamthamc@users.noreply.github.com"
      - run: git config --global user.name "Chaitanya K"
      - name: Release
        uses: actions/npm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          entrypoint: make
          args: release-ci
