on:
  push:
    branches:
      - master

name: Publish
jobs:
  release:
    name: PR Merges
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Setup Node
        if: endsWith(github.event.head_commit.message, '[ci skip]') == false
        uses: actions/setup-node@v1.4.1
        with:
          node-version: '13.x'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Release
        if: endsWith(github.event.head_commit.message, '[ci skip]') == false
        run: make release-ci
